### ISSUE TITLE
Add method to check if account already have phone

### ISSUE THREAD

**Issue by TrueCarry** [DoctorMcKay/node-steamstore#1]
I did this for myself, but this function queries not store but steamcommunity, so we should add cookies for that domain too. Because of that I'm not sure where it belongs, steam-user or steamstore. I hope you will find a place for this function. Also would be nice if you add function to check if 2FA already activated, but I don't know if it possible.

``` js
SteamStore.prototype.getPhoneData = function(callback) {
    var self = this;
    this.request.get({
        "uri": "https://steamcommunity.com/steamguard/phoneajax",
        "qs": {
            "op": "has_phone"
        },
        "json": true
    }, function(err, response, body) {
        if(self._checkHttpError(err, response, callback)) {
            return;
        }
        callback(null, {has_phone: (body.success && body.has_phone)});
    });
};
```

**Comment by DoctorMcKay** [comment]
Ugh, Valve. I don't like putting calls to steamcommunity.com in this module, but I guess all the account-management stuff is in here already and honestly that Steam Guard stuff should have been on the store site anyway. I'll add it here.
