### ISSUE TITLE
Bug, WalletCode: Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by fjexe** [DoctorMcKay/node-steamstore#24]
createWallet, checkWalletCode and redeemWalletCode always return an error:

```
components\account.js:353
                        if (!body.success && !body.detail && !body.wallet) {
TypeError: Cannot read property 'success' of undefined
```

Any other methods work fine.

**Comment by DoctorMcKay** [comment]
It seems to work fine on my end.

**Comment by fjexe** [comment]
Thanks, that was my mistake.

I did it like that: 
`           store.redeemWalletCode("ABCDE-ABCDE-ABCDE", (err) => {
                console.log(err);
            });`

Now I know how to do it and it works.

**Comment by fjexe** [comment]
It works for me, but I don’t think it should be:

**1:**
```
        store.getWalletBalance((error, data) => {
            console.log(data);
            store.checkWalletCode("ABCDE-12345-67890", (err) => {
                if (err) {
                    console.log(err.toString());
                } else {
                    console.log("OK");
                }
            });
        });
```
// returns:
{ formattedBalance: '$0.00 USD' }
OK

**2:**
```
            store.checkWalletCode("ABCDE-12345-67890", (err) => {
                if (err) {
                    console.log(err.toString());
                } else {
                    console.log("OK");
                }
            });
```
// returns:
account.js:394
if (!body.success && !body.detail && !body.wallet) {
TypeError: Cannot read property 'success' of undefined

**Total:**
store.checkWalletCode not working without a call getWalletBalance. Maybe I'm missing something?

**Comment by DoctorMcKay** [comment]
Closing this as checkWalletCode no longer works anyway.
