### ISSUE TITLE
Steam store has major update to wallet code redemption 

### ISSUE THREAD

**Issue by Minosviel** [DoctorMcKay/node-steamstore#25]
Steam store has been updated recently, and does not allow user to see information of the wallet code anymore (such as face value and formatted value). Wallet code will be redeemed straight away into the account.
As such, methods such as checkWalletCode() and redeemWalletCode() have stopped to work.

Now the only way to redeem the code is to POST via https://store.steampowered.com/account/ajaxredeemwalletcode/
with wallet_code and sessionid.

**Comment by DoctorMcKay** [comment]
Should be fixed in [v2.2.1](https://github.com/DoctorMcKay/node-steamstore/releases/tag/v2.2.1), but I don't have a wallet code on hand to test with, so please let me know if it doesn't work as expected.
