### ISSUE TITLE
Game Key redemption

### ISSUE THREAD

**Issue by saitho** [DoctorMcKay/node-steamstore#7]
I noticed that it is now possible to redeem the game keys via the web interface:
https://store.steampowered.com/account/registerkey

Redeeming a key sends a POST request to the URL https://store.steampowered.com/account/ajaxregisterkey/ with the parameters _product_key_ and _sessionid_. I saw that there was a sessionid that is used in this package.
Maybe it is possible to make this feature available for this package as well.

I might try that on the weekend and report to this issue. ;)

**Comment by saitho** [comment]
I got it working. :) Added a PR: https://github.com/DoctorMcKay/node-steamstore/pull/8

**Comment by DoctorMcKay** [comment]
Thanks for implementing this!

**Comment by saitho** [comment]
This wasn't merged yet, was it? There is still the open PR. https://github.com/DoctorMcKay/node-steamstore/pull/8

**Comment by Revadike** [comment]
> This wasn't merged yet, was it? There is still the open PR. #8

@DoctorMcKay
